# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python 3.11 image from the Python foundation.
FROM python:3.11-slim

# Set the working directory to /app
WORKDIR /app

# Install MS SQL Server prerequisites 
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    apt-transport-https \
    gnupg2 \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update

RUN ACCEPT_EULA=Y apt-get install -y --no-install-recommends msodbcsql18 \
    && apt-get install -y --no-install-recommends unixodbc-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements.txt file into the image
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application directory
COPY . .

# RUN apt-get update && apt-get install -y --no-install-recommends telnet iputils-ping traceroute && rm -rf /var/lib/apt/lists/*

# Install the package in development mode
RUN pip install -e .

# Command to run the MCP server
ENTRYPOINT ["python", "-m", "mssql_mcp_server"]